#!/bin/bash

# CGI wrapper for webservice
# that produces XML object with
# applicable request links.
# It supports CORS.
# Author: Bernardo Gomez

config="/usr/local/cgi-bin/" 
. ${config}webserver_environ     # dot in environ variables

# export all of the environ variables to my children
for env_var in $(cat ${config}webserver_environ | awk -F'=' '{print $1}')
do
  export ${env_var}
done


/path_to/webserver/bin/webserverAccess /path_to/webserver/bin/primo_request.py /path_to/webserver/config/primo_request.cfg
